---
- name: lsof - Run lsof
  command: lsof -P -T -X -n  # noqa no-changed-when
  register: _log4shell_lsof

- name: lsof - Process data from lsof
  set_fact:
    _log4shell_lsof_files: "{{ _log4shell_lsof.stdout_lines|default([]) | select('search', 'log4j-core-') | list | map('split', ' ') | map('last') | list | unique }}"
...
